routes/admin.php
<?php

Route::get('/dashboard', 'DashboardController@index')->name('dashboard')->middleware(['can:view administration']);

/** Permissions */
Route::prefix('permissions')->name('permissions.')->middleware('can:edit permissions')->group(function () {
    Route::get('list', 'PermissionsController@list')->name('list');
    Route::get('create', 'PermissionsController@create')->name('create');
    Route::get('update/{permission}', 'PermissionsController@update')->name('update');
    Route::get('delete/{permission}', 'PermissionsController@delete')->name('delete');
    Route::post('store', 'PermissionsController@store')->name('store');
});

/** Noleggiatori */
Route::prefix('noleggiatori')->name('noleggiatori.')->middleware('can:edit users')->group(function () {
    Route::get('list', 'NoleggiatoriController@list')->name('list');
    Route::get('create/{user}', 'NoleggiatoriController@create')->name('create');
    Route::get('update/{user}', 'NoleggiatoriController@update')->name('update');
    Route::get('delete/{user}', 'NoleggiatoriController@delete')->name('delete');
    Route::post('store', 'NoleggiatoriController@store')->name('store');
});

/** Users */
Route::prefix('users')->name('users.')->middleware('can:edit users')->group(function () {
    Route::get('list', 'UsersController@list')->name('list');
    Route::get('create', 'UsersController@create')->name('create');
    Route::get('update/{user}', 'UsersController@update')->name('update');
    Route::get('delete/{user}', 'UsersController@delete')->name('delete');
    Route::post('store', 'UsersController@store')->name('store');
});

/** Roles */
Route::prefix('roles')->name('roles.')->middleware('can:edit roles')->group(function () {
    Route::get('list', 'RolesController@list')->name('list');
    Route::get('create', 'RolesController@create')->name('create');
    Route::get('update/{role}', 'RolesController@update')->name('update');
    Route::get('delete/{role}', 'RolesController@delete')->name('delete');
    Route::post('store', 'RolesController@store')->name('store');
});

/** Markers */
Route::prefix('markers')->name('markers.')->middleware(['multiLanguage', 'can:edit markers'])->group(function () {
    Route::get('list', 'MarkersController@list')->name('list');
    Route::get('listOrphaned', 'MarkersController@orphaned')->name('orphaned');
    Route::get('orphanedDownload', 'MarkersController@orphanedDownload')->name('orphanedDownload');
    Route::get('getList', 'MarkersController@getList')->name('getList');
    Route::get('create','MarkersController@create')->name('create');
    Route::get('update/{marker}', 'MarkersController@update')->name('update');
    Route::get('delete/{marker}', 'MarkersController@delete')->name('delete');
    Route::get('search', 'MarkersController@search')->name('search');
    Route::post('store', 'MarkersController@store')->name('store');
    Route::get('distribusion/sync', 'MarkersController@distribusionSync')->name('distribusionSync')->middleware('can:update distribusion');
    Route::get('distribusion/singleSync', 'MarkersController@distribusionSingleSync')->name('distribusionSingleSync')->middleware('can:update distribusion');
    Route::get('distribusion/download/{locale}', 'MarkersController@distribusionDownload')->name('distribusionDownload')->middleware('can:update distribusion');
    Route::get('distribusion/addCounter', 'MarkersController@distribusionAddCounter')->name('distribusionAddCounter')->middleware('can:update distribusion');
    Route::get('distribusion/add', 'MarkersController@distribusionAdd')->name('distribusionAdd')->middleware('can:update distribusion');
    Route::get('distribusion/commands', 'MarkersController@distribusion')->name('distribusion')->middleware('can:update distribusion');
    Route::get('distribusion/prepareFor/{lang?}', 'MarkersController@prepareFor')->name('prepareFor')->middleware('can:update distribusion');
    Route::get('distribusion/removeToAdd', 'MarkersController@removeToAdd')->name('removeToAdd')->middleware('can:update distribusion');
});

/** Services */
Route::prefix('services')->name('services.')->middleware(['multiLanguage', 'can:edit services'])->group(function () {
    Route::get('list', 'ServicesController@list')->name('list');
    Route::get('create','ServicesController@create')->name('create');
    Route::get('update/{service}', 'ServicesController@update')->name('update');
    Route::get('delete/{service}', 'ServicesController@delete')->name('delete');
    Route::post('store', 'ServicesController@store')->name('store');
});

/** Retailers */
Route::prefix('retailers')->name('retailers.')->middleware(['multiLanguage', 'can:edit retailers'])->group(function () {
    Route::get('list', 'RetailersController@list')->name('list');
    Route::get('create','RetailersController@create')->name('create');
    Route::get('update/{retailer}', 'RetailersController@update')->name('update');
    Route::get('delete/{retailer}', 'RetailersController@delete')->name('delete');
    Route::post('store', 'RetailersController@store')->name('store');
});

/** Languages */
Route::prefix('languages')->name('languages.')->middleware(['can:edit languages'])->group(function () {
    Route::get('translations/list', 'LanguagesController@listTranslations')->name('listTranslations');
    Route::get('translations/edit/{language}/{translation}', 'LanguagesController@editTranslation')->name('editTranslation');
    Route::get('translations/new/{language}', 'LanguagesController@newTranslation')->name('newTranslation');
    Route::get('translations/duplicate/{language}/{translation}', 'LanguagesController@duplicateTranslation')->name('duplicateTranslation');
    Route::get('translations/doDuplicate/{newLang}/{translation}/{oldLang}', 'LanguagesController@doDuplicateTranslation')->name('doDuplicateTranslation');
    Route::post('translations/store/{language}', 'LanguagesController@storeTranslation')->name('storeTranslation');
});

/** Rental Request */
Route::prefix('rentRequests')->name('rentRequests.')->middleware(['can:administer rent requests'])->group(function () {
    Route::get('list', 'RentRequestsController@listNew')->name('listNew');
    Route::get('listCompleted', 'RentRequestsController@listCompleted')->name('listCompleted');
    Route::get('listSold', 'RentRequestsController@listSold')->name('listSold');
    Route::get('view/{rentRequest}', 'RentRequestsController@view')->name('view');
    Route::post('changeStatus/{rentRequest}', 'RentRequestsController@changeStatus')->name('changeStatus')->middleware(['can:change request status']);
});

/** Quotes */
Route::prefix('quotes')->name('quotes.')->middleware(['can:create quotes'])->group(function () {
    Route::get('list/{rentRequest}', 'QuotesController@listFor')->name('listFor');
    Route::get('new/{rentRequest}', 'QuotesController@create')->name('create');
    Route::get('edit/{rentRequest}/{quote}', 'QuotesController@edit')->name('edit');
    Route::get('pdf/{rentRequest}/{quote}', 'QuotesController@pdf')->name('pdf');
    Route::post('store/{rentRequest}', 'QuotesController@store')->name('store');
});

/** Promocodes */
Route::prefix('promocodes')->name('promocodes.')->middleware(['can:create promocodes'])->group(function () {
    Route::get('list', 'PromocodesController@list')->name('list');
    Route::get('new', 'PromocodesController@create')->name('create');
    Route::get('edit/{promocode}', 'PromocodesController@update')->name('edit');
    Route::post('store', 'PromocodesController@store')->name('store');
});

/** Notes */
Route::prefix('notes')->name('notes.')->middleware('can:write notes')->group(function () {
    Route::post('store', 'NotesController@store')->name('store');
});

/** Audits */
Route::prefix('audits')->name('audits.')->middleware('can:see audits')->group(function () {
    Route::post('view', 'AuditsController@view')->name('view');
});

/** Configuration */
Route::prefix('configurations')->name('configurations.')->middleware('can:edit configurations')->group(function () {
    Route::get('payments', 'SettingsController@listPayments')->name('listPayments');
    Route::get('distribusion', 'SettingsController@listDistribusion')->name('listDistribusion');
    Route::get('general', 'SettingsController@listGeneral')->name('listGeneral');
    Route::get('mail', 'SettingsController@listMail')->name('listMail');
    Route::post('store', 'SettingsController@store')->name('store');
});

/** Packages */
Route::prefix('packages')->name('packages.')->middleware(['multiLanguage', 'can:edit packages'])->group(function () {
    Route::get('list', 'PackagesController@list')->name('list');
    Route::get('create','PackagesController@create')->name('create');
    Route::get('update/{package}', 'PackagesController@update')->name('update');
    Route::get('delete/{package}', 'PackagesController@delete')->name('delete');
    Route::post('store', 'PackagesController@store')->name('store');
});

/** People Ranges */
Route::prefix('people_ranges')->name('people_ranges.')->middleware(['can:create people ranges'])->group(function () {
    Route::get('list', 'PeopleRangesController@list')->name('list');
    Route::get('new', 'PeopleRangesController@create')->name('create');
    Route::get('edit/{range}', 'PeopleRangesController@edit')->name('edit');
    Route::post('store', 'PeopleRangesController@store')->name('store');
    Route::get('delete/{range}', 'PeopleRangesController@delete')->name('delete');
});

/** Steps */
Route::prefix('steps')->name('steps.')->middleware(['can:edit steps'])->group( function() {
    Route::get('distribusionSteps/{rentRequest}', 'StepsController@distribusionSteps')->name('distribusionSteps');
    Route::get('distribusionSteps/edit/{quoteMarker}', 'StepsController@edit')->name('edit');
    Route::get('addTicket/{quoteMarker}', 'StepsController@addTicket')->name('addTicket');
    Route::get('editTicket/{quoteMarker}/{soldMarker}', 'StepsController@editTicket')->name('editTicket');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
 * Per i futuri programmatori: attenzione, io sono stato fregato, mi han chiesto così tante modifiche gratuite che ho perso 3 mesi di lavoro di moodifiche che hanno distrutto tutto il mio lavoro che ora è disordinato. E' un avviso di cortesia che lascio perchè avrei voluto saperlo io
 */

use App\Events\RequestCompleted;

Route::get('/prova', function () {

    $request = \App\Models\RentRequest::find(28);

    $request->status = 'completed';
    $request->save();

});

Route::group(['prefix' => 'messages'], function () {
    Route::get('/', ['as' => 'messages', 'uses' => 'Frontend\MessagesController@index']);
    Route::get('create', ['as' => 'messages.create', 'uses' => 'Frontend\MessagesController@create']);
    Route::post('/', ['as' => 'messages.store', 'uses' => 'Frontend\MessagesController@store']);
    Route::get('{id}', ['as' => 'messages.show', 'uses' => 'Frontend\MessagesController@show']);
    Route::put('{id}', ['as' => 'messages.update', 'uses' => 'Frontend\MessagesController@update']);
});

Route::get('/admin/dashboard', 'Admin\DashboardController@index');

Route::get('/logout', 'Auth\LoginController@logout')->name('logout' );
Auth::routes();

Route::get('/', 'Frontend\HomeController@index')->name('home');
Route::get('/home', 'Frontend\HomeController@index')->name('home');

Route::get('/lang/{locale}', 'Frontend\HomeController@setLang')->name('setLocale');

/** Noleggio */
Route::prefix('rent')->name('rent.')->group(function () {
    Route::get('/request/{type?}', 'Frontend\RentController@request')->name('noleggi.request');
    Route::post('/send', 'Frontend\RentController@saveRequest')->name('noleggi.save');
    Route::get('/rent-offer/{rentRequestUuid}', 'Frontend\RentController@generateOffer')->name('noleggi.offer');
    Route::get('/rent-partial-predict', 'Frontend\RentController@loadPartialPrice')->name('noleggi.partialOffer');
    Route::any('/rent-details/{rentRequestUuid}', 'Frontend\RentController@rentDetails')->name('noleggi.details');
    Route::post('/accept-offer/{rentRequest}', 'Frontend\RentController@acceptOffer')->name('noleggi.acceptOffer');
    Route::post('/final-step/{rentRequestUuid}', 'Frontend\RentController@finalStep')->name('noleggi.finalStep');
    Route::get('/confirm/{rentRequestUuid}', 'Frontend\RentController@confirm')->name('noleggi.confirm');
    Route::post('/complete/{rentRequestUuid}', 'Frontend\RentController@complete')->name('noleggi.complete');
});

Route::prefix('profile')->name('profile.')->middleware(['auth', 'can:see profile'])->group(function () {
    Route::get('/edit', 'Frontend\ProfileController@edit')->name('edit');
    Route::post('/store', 'Frontend\ProfileController@store')->name('store');
    Route::get('/requests', 'Frontend\ProfileController@requests')->name('requests');
    Route::get('/transactions', 'Frontend\ProfileController@transactions')->name('transactions');
    Route::get('/request/view/{rentRequestUuid}', 'Frontend\ProfileController@viewRequest')->name('viewRequest')->middleware(['quotePermission']);
    Route::get('/travel/view/{rentRequestUuid}', 'Frontend\ProfileController@viewTravel')->name('viewTravel')->middleware(['quotePermission']);
    Route::get('/request/delete', 'Frontend\ProfileController@deleteRequest')->name('deleteRequest');
    Route::get('/request/quotes/{rentRequestUuid}', 'Frontend\ProfileController@requestQuotes')->name('viewRequestQuotes')->middleware(['quotePermission']);
    Route::get('/request/singleQuote/{rentRequestUuid}/{quote}', 'Frontend\ProfileController@requestSingleQuote')->name('requestSingleQuote')->middleware(['quotePermission']);
    Route::any('/request/acceptQuote/{rentRequestUuid}/{quote}', 'Frontend\ProfileController@acceptQuote')->name('acceptQuote')->middleware(['quotePermission']);
});

/** Partner */
Route::prefix('partner')->name('partner.')->middleware(['auth', 'can:see partner'])->group(function () {
    Route::get('/', 'Frontend\PartnerController@index')->name('index');
    Route::get('/edit', 'Frontend\PartnerController@edit')->name('edit');
    Route::post('/store', 'Frontend\PartnerController@store')->name('store');
    Route::get('/opportunities', 'Frontend\PartnerController@opportunities')->name('opportunities');
    Route::get('/opportunity/{travel}', 'Frontend\PartnerController@opportunity')->name('opportunity')->middleware('noleggiatore');
    Route::get('/takeOpportunity/{travel}', 'Frontend\PartnerController@takeOpportunity')->name('takeOpportunity')->middleware('noleggiatore');
    Route::get('/ownedTravel/{travel}', 'Frontend\PartnerController@ownedTravel')->name('ownedTravel')->middleware('noleggiatore');
    Route::post('/ownedTravelStore/{travel}', 'Frontend\PartnerController@ownedTravelStore')->name('ownedTravelStore')->middleware('noleggiatore');
    Route::post('/ownedTravelAttach/{travel}', 'Frontend\PartnerController@fileUploads')->name('fileUploads')->middleware('noleggiatore');
    Route::get('/ownedTravelDeleteAttach/{travel}/{media}', 'Frontend\PartnerController@deleteAttachment')->name('deleteAttachment')->middleware('noleggiatore');
    Route::get('/ownedTravels', 'Frontend\PartnerController@ownedTravels')->name('ownedTravels');
});

/** Aggregati */
Route::prefix('join')->name('join.')->group(function () {
    Route::get('/', 'Frontend\JoinController@index')->name('index');
    Route::get('/ticket/{travelStep}', 'Frontend\JoinController@buyStep')->name('step')->middleware('auth');
});

/** Contact Us */
Route::get('/contact-us', 'Frontend\ContactUsController@index')->name('contactUs');
Route::get('/contact-us/submit', 'Frontend\ContactUsController@submit')->name('contactUsSubmit');

/** Contact Us */
Route::get('/faq', 'Frontend\FaqController@index')->name('faq');
Route::get('/faqs', 'Frontend\FaqController@index')->name('faqs');

/** About Us */
Route::get('/about-us', 'Frontend\AboutUsController@index')->name('aboutUs');

/** Coming Soon */
Route::get('/coming-soon', 'Frontend\ComingSoonController@index')->name('comingSoon');

/** Become Partner */
Route::get('/affiliation', 'Frontend\BecomePartnerController@index')->name('becomePartner');

/** Our Stops */
Route::get('/our-stops', 'Frontend\OurStopsController@index')->name('ourStops');
Route::get('/stops', 'Frontend\OurStopsController@index')->name('stops');

/** Our Bus */
Route::get('/our-bus', 'Frontend\OurBusController@index')->name('ourBus');
Route::get('/bus', 'Frontend\OurBusController@index')->name('bus');

/** Downloads */
Route::get('/travel/attachment/{media}', 'Frontend\DownloadsController@travelAttachment')->name('travelAttachmentDownload')->middleware(['checkDownload:travel']);

/** Socialite */
Route::get('redirect/{driver}', 'Auth\LoginController@redirectToProvider')
    ->name('login.provider')
    ->where('driver', implode('|', config('auth.socialite.drivers')));
Route::get('callback/{driver}', 'Auth\LoginController@handleProviderCallback')
    ->name('login.callback')
    ->where('driver', implode('|', config('auth.socialite.drivers')));

/** Payments */
Route::post('/checkout/payment/{order}/paypal', [
    'name' => 'PayPal Express Checkout',
    'as' => 'checkout.payment.paypal',
    'uses' => 'Frontend\PayPalController@checkout',
]);

Route::get('/paypal/checkout/{order}/completed', [
    'name' => 'PayPal Express Checkout',
    'as' => 'paypal.checkout.completed',
    'uses' => 'Frontend\PayPalController@completed',
]);

Route::get('/paypal/checkout/{order}/cancelled', [
    'name' => 'PayPal Express Checkout',
    'as' => 'paypal.checkout.cancelled',
    'uses' => 'Frontend\PayPalController@cancelled',
]);

Route::post('/webhook/paypal/{order?}/{env?}', [
    'name' => 'PayPal Express IPN',
    'as' => 'webhook.paypal.ipn',
    'uses' => 'Frontend\PayPalController@webhook',
]);

Route::post('/checkout/payment/{order}/stripe', [
    'name' => 'Stripe Checkout',
    'as' => 'checkout.payment.stripe',
    'uses' => 'Frontend\StripeController@checkout',
]);

resources/views/frontend/layout/shared/head.blade.php
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Buustle</title>

    <!-- Bootstrap CSS -->
    <link href="{{ asset('storage/assets/frontend/css/bootstrap/3.3.7/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('storage/assets/frontend/css/bootstrap-select.min.css') }}" rel="stylesheet">
    <!-- Slick Slider CSS -->
    <link rel="stylesheet" href="{{ asset('storage/assets/frontend/css/slick-slider-theme.min.css') }}">
    <link rel="stylesheet" href="{{ asset('storage/assets/frontend/css/slick-slider.min.css') }}">
    <!-- Our Custom CSS -->
    <link rel="stylesheet" href="{{ asset('storage/assets/frontend/css/style.css') }}">

    @yield('added-css')
</head>

resources/views/frontend/layout/shared/header.blade.php
<header class="header">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-2 col-lg-3">
                <button type="button" class="menu-mobile-icon hidden-md hidden-lg">
                    <div class="icon-bars collapsed">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </div>
                </button>
                <a href="{{ route('home') }}" title="Buustle" class="logo-container"><img class="logo-header" src="{{ asset('storage/assets/frontend/images/logo-buustle.svg') }}" alt="Buustle" title="Buustle"></a>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-10 col-lg-9 hidden-sm hidden-xs">
                <nav class="main-menu">
                    <ul>
                        <li class="lang">
                            <ul>
                                <li @if(\Illuminate\Support\Facades\App::getLocale() === 'it') class="active" @endif>
                                    <a href="{{ route('setLocale', ['locale' => 'it']) }}" title="ITA">@lang('header.lang_ITA')</a>
                                </li>
                                <span>/</span>
                                <li @if(\Illuminate\Support\Facades\App::getLocale() === 'en') class="active" @endif>
                                    <a href="{{ route('setLocale', ['locale' => 'en']) }}" title="EN">@lang('header.lang_EN')</a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a href="{{ route('rent.noleggi.request') }}" title="@lang('header.rent_request_title')">@lang('header.rent_request')</a>
                        </li>
                        <li>
                            <a href="{{ route('aboutUs') }}" title="@lang('header.about_us')">@lang('header.about_us')</a>
                        </li>
                        <li>
                            <a href="{{ route('contactUs') }}" title="@lang('header.contact_us_title')">@lang('header.contact_us')</a>
                        </li>
                        <li>
                            <a href="{{ route('becomePartner') }}" title="@lang('header.earn_with_us_title')">@lang('header.earn_with_us')</a>
                        </li>
                        @if ( \Illuminate\Support\Facades\Auth::check() )
                            <li class="menu-logged">
                                <div class="utente" style="background-image: url("");">
                                  <img src="{{ \Illuminate\Support\Facades\Auth::user()->getFirstMedia('avatar') ? \Illuminate\Support\Facades\Auth::user()->getFirstMedia('avatar')->getFullUrl() : asset('storage/assets/frontend/images/utente.png') }}" alt="{{ \Illuminate\Support\Facades\Auth::user()->profile->first_name }}" title="{{ \Illuminate\Support\Facades\Auth::user()->profile->first_name }}">
                                </div>
                                <ul class="menu">
                                    @if( \Illuminate\Support\Facades\Auth::user()->can('view administration'))
                                        <li>
                                            <a href="{{ route('admin.dashboard') }}" title="Amministrazione">Amministrazione</a>
                                        </li>
                                    @endif
                                    @if( \Illuminate\Support\Facades\Auth::user()->isValidNoleggiatore() )
                                        <li>
                                            <a href="{{ route('partner.index') }}" title="@lang('header.partner')">@lang('header.partner')</a>
                                        </li>
                                    @endif
                                  <li>
                                    <a href="{{ route('profile.requests') }}" title="@lang('header.profile')">@lang('header.profile')</a>
                                  </li>
                                  <li>
                                    <a href="{{ route('profile.transactions') }}" title="@lang('header.transactions')">@lang('header.transactions')</a>
                                  </li>
                                  <li>
                                    <a href="{{ route('logout') }}" class="red" title="@lang('global.logout_title')">@lang('global.logout')</a>
                                  </li>
                                </ul>
                            </li>
                        @else
                            <li class="menu-no-logged">
                                <a href="{{ route('login') }}" class="bttn bttn-orange "><span>@lang('global.login')</span></a>
                            </li>
                        @endif
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</header>

resources/views/frontend/layout/shared/sidebar.blade.php
<!-- Sidebar  -->
<div id="sidebar">
    <!--     <div class="menu-no-logged">
          <img class="banner-menu" src="images/banner-bg/profile-menu.svg" alt="Accedi" title="Accedi">
          <a href="#" class="bttn bttn-orange "><span>Accedi</span></a>
        </div> -->
    <div class="menu-logged">
        <img class="banner-menu"
             src="{{ asset('storage/assets/frontend/images/banner-bg/profile-menu-logged.svg') }}"
             alt="Profilo" title="Profilo">
        <div class="utente" style="background-image: url("");">
            <img src="{{
    \Illuminate\Support\Facades\Auth::user() && \Illuminate\Support\Facades\Auth::user()->getFirstMedia('avatar')
    ? \Illuminate\Support\Facades\Auth::user()->getFirstMedia('avatar')->getFullUrl()
    : asset('storage/assets/frontend/images/utente.png') }}"
                 alt="{{ \Illuminate\Support\Facades\Auth::user() ? \Illuminate\Support\Facades\Auth::user()->profile->first_name : 'User' }}" title="{{ \Illuminate\Support\Facades\Auth::user() ? \Illuminate\Support\Facades\Auth::user()->profile->first_name : 'User' }}">
        </div>
        <span class="name">{{ \Illuminate\Support\Facades\Auth::user() ? \Illuminate\Support\Facades\Auth::user()->profile->first_name : 'User' }}</span>
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <ul class="menu">
                        @if ( \Illuminate\Support\Facades\Auth::check() )
                            @if( \Illuminate\Support\Facades\Auth::user()->can('view administration'))
                                <li>
                                    <a href="{{ route('admin.dashboard') }}" title="Amministrazione">Amministrazione</a>
                                </li>
                            @endif
                            @if( \Illuminate\Support\Facades\Auth::user()->isValidNoleggiatore() )
                                <li>
                                    <a href="{{ route('partner.index') }}" title="@lang('header.partner')">@lang('header.partner')</a>
                                </li>
                            @endif
                            <li>
                                <a href="{{ route('profile.requests') }}" title="@lang('header.profile')">@lang('header.profile')</a>
                            </li>
                            <li>
                                <a href="{{ route('profile.transactions') }}" title="@lang('header.transactions')">@lang('header.transactions')</a>
                            </li>
                            <li>
                                <a href="{{ route('logout') }}" class="red" title="@lang('global.logout_title')">@lang('global.logout')</a>
                            </li>
                        @else
                            <li class="menu-no-logged">
                                <a href="{{ route('login') }}" class="bttn bttn-orange "><span>@lang('global.login')</span></a>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="main-menu">
        <div class="container">
            <nav class="nav-menu">
                <ul>
                    <li class="lang">
                        <ul>
                            <li @if(\Illuminate\Support\Facades\App::getLocale() === 'it') class="active" @endif>
                                <a href="{{ route('setLocale', ['locale' => 'it']) }}" title="ITA">@lang('header.lang_ITA')</a>
                            </li>
                            <span>/</span>
                            <li @if(\Illuminate\Support\Facades\App::getLocale() === 'en') class="active" @endif>
                                <a href="{{ route('setLocale', ['locale' => 'en']) }}" title="EN">@lang('header.lang_EN')</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="{{ route('rent.noleggi.request') }}" title="@lang('header.rent_request_title')">@lang('header.rent_request')</a>
                    </li>
                    <li>
                        <a href="{{ route('aboutUs') }}" title="@lang('header.about_us')">@lang('header.about_us')</a>
                    </li>
                    <li>
                        <a href="{{ route('contactUs') }}" title="@lang('header.contact_us_title')">@lang('header.contact_us')</a>
                    </li>
                    <li>
                        <a href="{{ route('becomePartner') }}" title="@lang('header.earn_with_us_title')">@lang('header.earn_with_us')</a>
                    </li>
                </ul>
            </nav>
            <ul class="submenu">
                <li><a href="{{ route('aboutUs') }}" title="@lang('footer.about_us')">@lang('footer.about_us')</a></li>
                <li><a href="{{ route('ourBus') }}" title="@lang('footer.our_bus')">@lang('footer.our_bus')</a></li>
                <li><a href="{{ route('ourStops') }}" title="@lang('footer.our_stations')">@lang('footer.our_stations')</a></li>
                <li><a href="{{ route('faq') }}" title="@lang('footer.faq')">@lang('footer.faq')</a></li>
                <li><a href="#" title="@lang('footer.general_conditions')">@lang('footer.general_conditions')</a></li>
                <li><a href="#" title="@lang('footer.privacy')">@lang('footer.privacy')</a></li>
                <li><a href="#" title="@lang('footer.cookies')">@lang('footer.cookies')</a></li>
            </ul>
        </div>
    </div>
</div>