routes/admin.php
<?php

Route::get('/dashboard', 'DashboardController@index')->name('dashboard')->middleware(['can:view administration']);

/** Permissions */
Route::prefix('permissions')->name('permissions.')->middleware('can:edit permissions')->group(function () {
    Route::get('list', 'PermissionsController@list')->name('list');
    Route::get('create', 'PermissionsController@create')->name('create');
    Route::get('update/{permission}', 'PermissionsController@update')->name('update');
    Route::get('delete/{permission}', 'PermissionsController@delete')->name('delete');
    Route::post('store', 'PermissionsController@store')->name('store');
});

/** Noleggiatori */
Route::prefix('noleggiatori')->name('noleggiatori.')->middleware('can:edit users')->group(function () {
    Route::get('list', 'NoleggiatoriController@list')->name('list');
    Route::get('create/{user}', 'NoleggiatoriController@create')->name('create');
    Route::get('update/{user}', 'NoleggiatoriController@update')->name('update');
    Route::get('delete/{user}', 'NoleggiatoriController@delete')->name('delete');
    Route::post('store', 'NoleggiatoriController@store')->name('store');
});

/** Users */
Route::prefix('users')->name('users.')->middleware('can:edit users')->group(function () {
    Route::get('list', 'UsersController@list')->name('list');
    Route::get('create', 'UsersController@create')->name('create');
    Route::get('update/{user}', 'UsersController@update')->name('update');
    Route::get('delete/{user}', 'UsersController@delete')->name('delete');
    Route::post('store', 'UsersController@store')->name('store');
});

/** Roles */
Route::prefix('roles')->name('roles.')->middleware('can:edit roles')->group(function () {
    Route::get('list', 'RolesController@list')->name('list');
    Route::get('create', 'RolesController@create')->name('create');
    Route::get('update/{role}', 'RolesController@update')->name('update');
    Route::get('delete/{role}', 'RolesController@delete')->name('delete');
    Route::post('store', 'RolesController@store')->name('store');
});

/** Markers */
Route::prefix('markers')->name('markers.')->middleware(['multiLanguage', 'can:edit markers'])->group(function () {
    Route::get('list', 'MarkersController@list')->name('list');
    Route::get('listOrphaned', 'MarkersController@orphaned')->name('orphaned');
    Route::get('orphanedDownload', 'MarkersController@orphanedDownload')->name('orphanedDownload');
    Route::get('getList', 'MarkersController@getList')->name('getList');
    Route::get('create','MarkersController@create')->name('create');
    Route::get('update/{marker}', 'MarkersController@update')->name('update');
    Route::get('delete/{marker}', 'MarkersController@delete')->name('delete');
    Route::get('search', 'MarkersController@search')->name('search');
    Route::post('store', 'MarkersController@store')->name('store');
    Route::get('distribusion/sync', 'MarkersController@distribusionSync')->name('distribusionSync')->middleware('can:update distribusion');
    Route::get('distribusion/singleSync', 'MarkersController@distribusionSingleSync')->name('distribusionSingleSync')->middleware('can:update distribusion');
    Route::get('distribusion/download/{locale}', 'MarkersController@distribusionDownload')->name('distribusionDownload')->middleware('can:update distribusion');
    Route::get('distribusion/addCounter', 'MarkersController@distribusionAddCounter')->name('distribusionAddCounter')->middleware('can:update distribusion');
    Route::get('distribusion/add', 'MarkersController@distribusionAdd')->name('distribusionAdd')->middleware('can:update distribusion');
    Route::get('distribusion/commands', 'MarkersController@distribusion')->name('distribusion')->middleware('can:update distribusion');
    Route::get('distribusion/prepareFor/{lang?}', 'MarkersController@prepareFor')->name('prepareFor')->middleware('can:update distribusion');
    Route::get('distribusion/removeToAdd', 'MarkersController@removeToAdd')->name('removeToAdd')->middleware('can:update distribusion');
});

/** Services */
Route::prefix('services')->name('services.')->middleware(['multiLanguage', 'can:edit services'])->group(function () {
    Route::get('list', 'ServicesController@list')->name('list');
    Route::get('create','ServicesController@create')->name('create');
    Route::get('update/{service}', 'ServicesController@update')->name('update');
    Route::get('delete/{service}', 'ServicesController@delete')->name('delete');
    Route::post('store', 'ServicesController@store')->name('store');
});

/** Retailers */
Route::prefix('retailers')->name('retailers.')->middleware(['multiLanguage', 'can:edit retailers'])->group(function () {
    Route::get('list', 'RetailersController@list')->name('list');
    Route::get('create','RetailersController@create')->name('create');
    Route::get('update/{retailer}', 'RetailersController@update')->name('update');
    Route::get('delete/{retailer}', 'RetailersController@delete')->name('delete');
    Route::post('store', 'RetailersController@store')->name('store');
});

/** Languages */
Route::prefix('languages')->name('languages.')->middleware(['can:edit languages'])->group(function () {
    Route::get('translations/list', 'LanguagesController@listTranslations')->name('listTranslations');
    Route::get('translations/edit/{language}/{translation}', 'LanguagesController@editTranslation')->name('editTranslation');
    Route::get('translations/new/{language}', 'LanguagesController@newTranslation')->name('newTranslation');
    Route::get('translations/duplicate/{language}/{translation}', 'LanguagesController@duplicateTranslation')->name('duplicateTranslation');
    Route::get('translations/doDuplicate/{newLang}/{translation}/{oldLang}', 'LanguagesController@doDuplicateTranslation')->name('doDuplicateTranslation');
    Route::post('translations/store/{language}', 'LanguagesController@storeTranslation')->name('storeTranslation');
});

/** Rental Request */
Route::prefix('rentRequests')->name('rentRequests.')->middleware(['can:administer rent requests'])->group(function () {
    Route::get('list', 'RentRequestsController@listNew')->name('listNew');
    Route::get('listCompleted', 'RentRequestsController@listCompleted')->name('listCompleted');
    Route::get('listSold', 'RentRequestsController@listSold')->name('listSold');
    Route::get('view/{rentRequest}', 'RentRequestsController@view')->name('view');
    Route::post('changeStatus/{rentRequest}', 'RentRequestsController@changeStatus')->name('changeStatus')->middleware(['can:change request status']);
});

/** Quotes */
Route::prefix('quotes')->name('quotes.')->middleware(['can:create quotes'])->group(function () {
    Route::get('list/{rentRequest}', 'QuotesController@listFor')->name('listFor');
    Route::get('new/{rentRequest}', 'QuotesController@create')->name('create');
    Route::get('edit/{rentRequest}/{quote}', 'QuotesController@edit')->name('edit');
    Route::get('pdf/{rentRequest}/{quote}', 'QuotesController@pdf')->name('pdf');
    Route::post('store/{rentRequest}', 'QuotesController@store')->name('store');
});

/** Promocodes */
Route::prefix('promocodes')->name('promocodes.')->middleware(['can:create promocodes'])->group(function () {
    Route::get('list', 'PromocodesController@list')->name('list');
    Route::get('new', 'PromocodesController@create')->name('create');
    Route::get('edit/{promocode}', 'PromocodesController@update')->name('edit');
    Route::post('store', 'PromocodesController@store')->name('store');
});

/** Notes */
Route::prefix('notes')->name('notes.')->middleware('can:write notes')->group(function () {
    Route::post('store', 'NotesController@store')->name('store');
});

/** Audits */
Route::prefix('audits')->name('audits.')->middleware('can:see audits')->group(function () {
    Route::post('view', 'AuditsController@view')->name('view');
});

/** Configuration */
Route::prefix('configurations')->name('configurations.')->middleware('can:edit configurations')->group(function () {
    Route::get('payments', 'SettingsController@listPayments')->name('listPayments');
    Route::get('distribusion', 'SettingsController@listDistribusion')->name('listDistribusion');
    Route::get('general', 'SettingsController@listGeneral')->name('listGeneral');
    Route::get('mail', 'SettingsController@listMail')->name('listMail');
    Route::post('store', 'SettingsController@store')->name('store');
});

/** Packages */
Route::prefix('packages')->name('packages.')->middleware(['multiLanguage', 'can:edit packages'])->group(function () {
    Route::get('list', 'PackagesController@list')->name('list');
    Route::get('create','PackagesController@create')->name('create');
    Route::get('update/{package}', 'PackagesController@update')->name('update');
    Route::get('delete/{package}', 'PackagesController@delete')->name('delete');
    Route::post('store', 'PackagesController@store')->name('store');
});

/** People Ranges */
Route::prefix('people_ranges')->name('people_ranges.')->middleware(['can:create people ranges'])->group(function () {
    Route::get('list', 'PeopleRangesController@list')->name('list');
    Route::get('new', 'PeopleRangesController@create')->name('create');
    Route::get('edit/{range}', 'PeopleRangesController@edit')->name('edit');
    Route::post('store', 'PeopleRangesController@store')->name('store');
    Route::get('delete/{range}', 'PeopleRangesController@delete')->name('delete');
});

/** Steps */
Route::prefix('steps')->name('steps.')->middleware(['can:edit steps'])->group( function() {
    Route::get('distribusionSteps/{rentRequest}', 'StepsController@distribusionSteps')->name('distribusionSteps');
    Route::get('distribusionSteps/edit/{quoteMarker}', 'StepsController@edit')->name('edit');
    Route::get('addTicket/{quoteMarker}', 'StepsController@addTicket')->name('addTicket');
    Route::get('editTicket/{quoteMarker}/{soldMarker}', 'StepsController@editTicket')->name('editTicket');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
 * Per i futuri programmatori: attenzione, io sono stato fregato, mi han chiesto così tante modifiche gratuite che ho perso 3 mesi di lavoro di moodifiche che hanno distrutto tutto il mio lavoro che ora è disordinato. E' un avviso di cortesia che lascio perchè avrei voluto saperlo io
 */

use App\Events\RequestCompleted;

Route::get('/prova', function () {

    $request = \App\Models\RentRequest::find(28);

    $request->status = 'completed';
    $request->save();

});

Route::group(['prefix' => 'messages'], function () {
    Route::get('/', ['as' => 'messages', 'uses' => 'Frontend\MessagesController@index']);
    Route::get('create', ['as' => 'messages.create', 'uses' => 'Frontend\MessagesController@create']);
    Route::post('/', ['as' => 'messages.store', 'uses' => 'Frontend\MessagesController@store']);
    Route::get('{id}', ['as' => 'messages.show', 'uses' => 'Frontend\MessagesController@show']);
    Route::put('{id}', ['as' => 'messages.update', 'uses' => 'Frontend\MessagesController@update']);
});

Route::get('/admin/dashboard', 'Admin\DashboardController@index');

Route::get('/logout', 'Auth\LoginController@logout')->name('logout' );
Auth::routes();

Route::get('/', 'Frontend\HomeController@index')->name('home');
Route::get('/home', 'Frontend\HomeController@index')->name('home');

Route::get('/lang/{locale}', 'Frontend\HomeController@setLang')->name('setLocale');

/** Noleggio */
Route::prefix('rent')->name('rent.')->group(function () {
    Route::get('/request/{type?}', 'Frontend\RentController@request')->name('noleggi.request');
    Route::post('/send', 'Frontend\RentController@saveRequest')->name('noleggi.save');
    Route::get('/rent-offer/{rentRequestUuid}', 'Frontend\RentController@generateOffer')->name('noleggi.offer');
    Route::get('/rent-partial-predict', 'Frontend\RentController@loadPartialPrice')->name('noleggi.partialOffer');
    Route::any('/rent-details/{rentRequestUuid}', 'Frontend\RentController@rentDetails')->name('noleggi.details');
    Route::post('/accept-offer/{rentRequest}', 'Frontend\RentController@acceptOffer')->name('noleggi.acceptOffer');
    Route::post('/final-step/{rentRequestUuid}', 'Frontend\RentController@finalStep')->name('noleggi.finalStep');
    Route::get('/confirm/{rentRequestUuid}', 'Frontend\RentController@confirm')->name('noleggi.confirm');
    Route::post('/complete/{rentRequestUuid}', 'Frontend\RentController@complete')->name('noleggi.complete');
});

Route::prefix('profile')->name('profile.')->middleware(['auth', 'can:see profile'])->group(function () {
    Route::get('/edit', 'Frontend\ProfileController@edit')->name('edit');
    Route::post('/store', 'Frontend\ProfileController@store')->name('store');
    Route::get('/requests', 'Frontend\ProfileController@requests')->name('requests');
    Route::get('/transactions', 'Frontend\ProfileController@transactions')->name('transactions');
    Route::get('/request/view/{rentRequestUuid}', 'Frontend\ProfileController@viewRequest')->name('viewRequest')->middleware(['quotePermission']);
    Route::get('/travel/view/{rentRequestUuid}', 'Frontend\ProfileController@viewTravel')->name('viewTravel')->middleware(['quotePermission']);
    Route::get('/request/delete', 'Frontend\ProfileController@deleteRequest')->name('deleteRequest');
    Route::get('/request/quotes/{rentRequestUuid}', 'Frontend\ProfileController@requestQuotes')->name('viewRequestQuotes')->middleware(['quotePermission']);
    Route::get('/request/singleQuote/{rentRequestUuid}/{quote}', 'Frontend\ProfileController@requestSingleQuote')->name('requestSingleQuote')->middleware(['quotePermission']);
    Route::any('/request/acceptQuote/{rentRequestUuid}/{quote}', 'Frontend\ProfileController@acceptQuote')->name('acceptQuote')->middleware(['quotePermission']);
});

/** Partner */
Route::prefix('partner')->name('partner.')->middleware(['auth', 'can:see partner'])->group(function () {
    Route::get('/', 'Frontend\PartnerController@index')->name('index');
    Route::get('/edit', 'Frontend\PartnerController@edit')->name('edit');
    Route::post('/store', 'Frontend\PartnerController@store')->name('store');
    Route::get('/opportunities', 'Frontend\PartnerController@opportunities')->name('opportunities');
    Route::get('/opportunity/{travel}', 'Frontend\PartnerController@opportunity')->name('opportunity')->middleware('noleggiatore');
    Route::get('/takeOpportunity/{travel}', 'Frontend\PartnerController@takeOpportunity')->name('takeOpportunity')->middleware('noleggiatore');
    Route::get('/ownedTravel/{travel}', 'Frontend\PartnerController@ownedTravel')->name('ownedTravel')->middleware('noleggiatore');
    Route::post('/ownedTravelStore/{travel}', 'Frontend\PartnerController@ownedTravelStore')->name('ownedTravelStore')->middleware('noleggiatore');
    Route::post('/ownedTravelAttach/{travel}', 'Frontend\PartnerController@fileUploads')->name('fileUploads')->middleware('noleggiatore');
    Route::get('/ownedTravelDeleteAttach/{travel}/{media}', 'Frontend\PartnerController@deleteAttachment')->name('deleteAttachment')->middleware('noleggiatore');
    Route::get('/ownedTravels', 'Frontend\PartnerController@ownedTravels')->name('ownedTravels');
});

/** Aggregati */
Route::prefix('join')->name('join.')->group(function () {
    Route::get('/', 'Frontend\JoinController@index')->name('index');
    Route::get('/ticket/{travelStep}', 'Frontend\JoinController@buyStep')->name('step')->middleware('auth');
});

/** Contact Us */
Route::get('/contact-us', 'Frontend\ContactUsController@index')->name('contactUs');
Route::get('/contact-us/submit', 'Frontend\ContactUsController@submit')->name('contactUsSubmit');

/** Contact Us */
Route::get('/faq', 'Frontend\FaqController@index')->name('faq');
Route::get('/faqs', 'Frontend\FaqController@index')->name('faqs');

/** About Us */
Route::get('/about-us', 'Frontend\AboutUsController@index')->name('aboutUs');

/** Coming Soon */
Route::get('/coming-soon', 'Frontend\ComingSoonController@index')->name('comingSoon');

/** Become Partner */
Route::get('/affiliation', 'Frontend\BecomePartnerController@index')->name('becomePartner');

/** Our Stops */
Route::get('/our-stops', 'Frontend\OurStopsController@index')->name('ourStops');
Route::get('/stops', 'Frontend\OurStopsController@index')->name('stops');

/** Our Bus */
Route::get('/our-bus', 'Frontend\OurBusController@index')->name('ourBus');
Route::get('/bus', 'Frontend\OurBusController@index')->name('bus');

/** Downloads */
Route::get('/travel/attachment/{media}', 'Frontend\DownloadsController@travelAttachment')->name('travelAttachmentDownload')->middleware(['checkDownload:travel']);

/** Socialite */
Route::get('redirect/{driver}', 'Auth\LoginController@redirectToProvider')
    ->name('login.provider')
    ->where('driver', implode('|', config('auth.socialite.drivers')));
Route::get('callback/{driver}', 'Auth\LoginController@handleProviderCallback')
    ->name('login.callback')
    ->where('driver', implode('|', config('auth.socialite.drivers')));

/** Payments */
Route::post('/checkout/payment/{order}/paypal', [
    'name' => 'PayPal Express Checkout',
    'as' => 'checkout.payment.paypal',
    'uses' => 'Frontend\PayPalController@checkout',
]);

Route::get('/paypal/checkout/{order}/completed', [
    'name' => 'PayPal Express Checkout',
    'as' => 'paypal.checkout.completed',
    'uses' => 'Frontend\PayPalController@completed',
]);

Route::get('/paypal/checkout/{order}/cancelled', [
    'name' => 'PayPal Express Checkout',
    'as' => 'paypal.checkout.cancelled',
    'uses' => 'Frontend\PayPalController@cancelled',
]);

Route::post('/webhook/paypal/{order?}/{env?}', [
    'name' => 'PayPal Express IPN',
    'as' => 'webhook.paypal.ipn',
    'uses' => 'Frontend\PayPalController@webhook',
]);

Route::post('/checkout/payment/{order}/stripe', [
    'name' => 'Stripe Checkout',
    'as' => 'checkout.payment.stripe',
    'uses' => 'Frontend\StripeController@checkout',
]);

resources/views/frontend/partner/opportunities/owned.blade.php
@extends('frontend.layout.main')

@section('added-css')
    @parent

@endsection

@section('content')

    <div class="menu-mobile-overlay"></div>

    <div class="profilo-utente">
        <picture class="banner-menu">
            <source srcset="{{ asset('storage/assets/frontend/images/banner-bg/profile-menu-logged.svg') }}" media="(max-width: 767px)">
            <source srcset="{{ asset('storage/assets/frontend/images/banner-bg/profile-menu-logged-desktop.svg') }}" media="(min-width: 768px)">
            <source srcset="{{ asset('storage/assets/frontend/images/banner-bg/profile-menu-logged.svg') }}">
            <img srcset="{{ asset('storage/assets/frontend/images/banner-bg/profile-menu-logged.svg') }}" alt="Buustle" title="Buustle">
        </picture>
        <div class="utente">
            <img src="{{ $noleggiatore->getFirstMedia('logo') ? $noleggiatore->getFirstMedia('logo')->getFullUrl() : asset('storage/assets/frontend/images/utente.png') }}" alt="{{ $noleggiatore->retailer->name }}" title="{{ $noleggiatore->retailer->name }}">
        </div>
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <span class="name">{{ $noleggiatore->retailer->name }}<a href="{{ route('partner.edit') }}" title="Edit"><img src="{{ asset('storage/assets/frontend/images/icons-svg/edit.svg') }}" alt="@lang('partner.edit')" title="@lang('partner.edit')"></a></span>
                    <ul class="info">
                        <li><img src="{{ asset('storage/assets/frontend/images/icons-svg/mail-profile.svg') }}" alt="Email" title="Email"><span>{{ \Illuminate\Support\Facades\Auth::user()->email }}</span></li>
                        <li><img src="{{ asset('storage/assets/frontend/images/icons-svg/telefono.svg') }}" alt="Telefono" title="Telefono"><span>{{ $noleggiatore->phone ?? '-' }}</span></li>
                        <li><img src="{{ asset('storage/assets/frontend/images/icons-svg/casa.svg') }}" alt="Indirizzo" title="Indirizzo"><span>{{ $noleggiatore->address ?? '-' }}</span></li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="bg-ivory">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12 col-md-offset-2">
                        <ul class="nav-profile">
                            <li><a href="{{ route('partner.index') }}" title="@lang('partner.rent_requests_area')">@lang('partner.rent_requests_area')</a></li>
                            <li class="active"><a href="{{ route('partner.ownedTravels') }}" title="@lang('partner.rent_requests_accepted')">@lang('partner.rent_requests_accepted')</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <div class="bg-ivory">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="scheda01 scheda01-b padding-0-60">
                            <div class="row">
                                @forelse( $travels as $travel )
                                    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4 inner">
                                        <div>
                                            <a href="{{ route( 'partner.ownedTravel', ['travel' => $travel] ) }}">
                                                <div class="row">
                                                    <div class="col-xs-10 col-xs-offset-1">
                                                        <div class="row viaggi">
                                                            <div class="col-xs-5">
                                                                <span class="citta">{{ $travel->getFirstStep()->startMarker->region->name_it }}</span>
                                                                <span class="indirizzo">{{ trim($travel->getFirstStep()->startMarker->name) }}</span>
                                                                <span class="data">{{ \Carbon\Carbon::parse($travel->getFirstStep()->start_time)->formatLocalized('%e %B %g - %H:%m') }}</span>
                                                            </div>
                                                            <div class="col-xs-2"><img src="{{ asset('storage/assets/frontend/images/icons-svg/freccia-doppio-senso.svg') }}" alt="_" title="_"></div>
                                                            <div class="col-xs-5">
                                                                <span class="citta">{{ $travel->getLastStep()->endMarker->region->name_it }}</span>
                                                                <span class="indirizzo">{{ trim($travel->getLastStep()->endMarker->name) }}</span>
                                                                <span class="data">{{ \Carbon\Carbon::parse($travel->getLastStep()->endMarker->end_time)->formatLocalized('%e %B %g - %H:%m') }}</span>
                                                            </div>
                                                        </div>
                                                        <div class="row credito-posti">
                                                            <div class="col-xs-6">
                                                                <div class="span"><img src="{{ asset('storage/assets/frontend/images/icons-svg/passeggeri-2.svg') }}" alt="@lang('profile.rent_confirmed_people')" title="@lang('profile.rent_confirmed_people')"><span class="steel">{{ $travel->people }}</span></div>
                                                                <span class="per-biglietto">@lang('profile.rent_confirmed_people')</span>
                                                            </div>
                                                            <div class="col-xs-6">
                                                                <div class="span posti"><img src="{{ asset('storage/assets/frontend/images/icons-svg/bus-2.svg') }}" alt="@lang('profile.rent_vehicle_requested')" title="@lang('profile.rent_vehicle_requested')"><span>{{ $travel->package->name }}</span></div>
                                                                <span class="per-biglietto">@lang('profile.rent_vehicle_requested')</span>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </a>
                                        </div>
                                    </div>
                                @empty
                                    @lang('profile.no_active_requests')
                                @endforelse
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

@endsection

@section('js-scripts')
    @parent

@endsection

@section('added-js')

@endsection